refactor dir struct

diff --git a/devtools/bin/buildenv b/devtools/bin/buildenv
--- a/devtools/bin/buildenv
+++ b/devtools/bin/buildenv
@@ -2,13 +2,14 @@
 
 tag=${1:-latest}
 
+STORAGE=/mnt/data/zynewdev
 echo "Creating the src directory, home link, and a named volume"
-mkdir -p /src/
+sudo mkdir -p $STORAGE
 # hard code, whatever.
-chown zy:zy /src
-ln -sf /src ~/dev
-ln -sf /src/goroot ~/goroot
-docker volume create -d local -o o=bind -o device=/src src
+chown -R `id -u`:`id -g` $STORAGE
+ln -sf $STORAGE ~/dev
+ln -sf $STORAGE/goroot ~/goroot
+docker volume create -d local -o o=bind -o device=$STORAGE src
 
 echo "Copying the bash configuration and local vim completion"
 cp general/bashrc ~/.bashrc
@@ -18,14 +19,22 @@ echo "Creating development network"
 docker network create --attachable devnet
 
 echo "Building work environment image"
-docker build -t dev .
+docker build -t dev docker
+
+if [ $? -ne 0 ]; then
+  echo "Dev image building failure"
+  exit 1
+fi
+
+echo "Setting up working user ID"
+docker run -it --rm -v src:/src --name dev -v /var/run/docker.sock:/var/run/docker.sock dev:${tag} setup_user.sh `id -u` `id -g` $USER $USER
 
 echo "Do some stupid vim setup"
-docker run -it --rm -v src:/src --name develop -v /var/run/docker.sock:/var/run/docker.sock dev:${tag} setup_vim.sh
+docker run --user $USER:$USER --group-add docker --group-add sudo -it --rm -v src:/src --name develop -v /var/run/docker.sock:/var/run/docker.sock dev:${tag} setup_vim.sh
 
 echo "Repeat the vim setup for external environment, now the /src should already have go dependency setup"
 bin/setup_vim.sh local
 
 echo "Setting up repository for the first time"
-docker run -it --rm -v src:/src dev:${tag} setup_repo.sh
+docker run --user $USER:$USER --group-add docker --group-add sudo -it --rm -v src:/src dev:${tag} -v /var/run/docker.sock:/var/run/docker.sock setup_repo.sh
 
